export const regDataByIdShared = {
  statusCode: '200',
  status: 'success',
  tournament: {
    tournament_id: 3751,
    tournament_name: 'Tournament 16DEC',
    tournament_pic:
      '/images/tournaments/1608097188-Screen Shot 2020-12-14 at 5.40.27 pm.png',
    date: 'DECEMBER |THURSDAY 3RD - 6TH @ 08:00 AM-07:00 PM',
    court_name: 'Feriton Spur',
    street_address: 'Kirkland',
    city: 'Kirkland',
    zip: 98033,
    division: [
      {
        division_id: 11848,
        division_name: 'Coed 50 AA',
        format: 2,
        team: [
          {
            team_id: 108327,
            team_name: 'Team1',
            waiting: 0,
            player: [
              {
                avp_id: 1037453,
                first_name: 'Brett',
                last_name: 'Ryan',
                city: 'Seattle',
                state_code: 'Wa',
                status: 'Available',
                profile_pic: '/images/promoters/abc.jpeg',
                team_id: 108327,
                points: '136 pts',
              },
              {
                avp_id: 1037591,
                first_name: 'Tony',
                last_name: 'Pressacco',
                city: 'bellevue',
                state_code: 'WA',
                status: 'Available',
                profile_pic: '',
                team_id: 108327,
                points: '104 pts',
              },
            ],
          },
          {
            team_id: 108405,
            team_name: 'Team2',
            waiting: 0,
            player: [
              {
                avp_id: 1025752,
                first_name: 'Catherine',
                last_name: 'Veigl',
                city: 'Floral Park',
                state_code: 'NY',
                status: 'Available',
                profile_pic: '',
                team_id: 108405,
                points: '0 pts',
              },
              null,
            ],
          },
          {
            team_id: 108408,
            team_name: 'Team3',
            waiting: 0,
            player: [null, null],
          },
          {
            team_id: 108409,
            team_name: 'Team4',
            waiting: 0,
            player: [null, null],
          },
          {
            team_id: 0,
            team_name: 'Team1',
            waiting: 0,
            player: [null, null],
          },
          {
            team_id: 0,
            team_name: 'Team2',
            waiting: 0,
            player: [null, null],
          },
          {
            team_id: 0,
            team_name: 'Team3',
            waiting: 0,
            player: [null, null],
          },
          {
            team_id: 0,
            team_name: 'Team4',
            waiting: 0,
            player: [null, null],
          },
        ],
      },
      {
        division_id: 11849,
        division_name: 'Coed 50 BB',
        format: 2,
        team: [
          {
            team_id: 108328,
            team_name: 'Team1',
            waiting: 0,
            player: [
              {
                avp_id: 100009151,
                first_name: 'Sandra ',
                last_name: 'Franz',
                city: 'Mill Creek',
                state_code: 'WA',
                status: 'Available',
                profile_pic: '',
                team_id: 108328,
                points: '100 pts',
              },
              null,
            ],
          },
          {
            team_id: 0,
            team_name: 'Team1',
            waiting: 0,
            player: [null, null],
          },
          {
            team_id: 0,
            team_name: 'Team2',
            waiting: 0,
            player: [null, null],
          },
          {
            team_id: 0,
            team_name: 'Team3',
            waiting: 0,
            player: [null, null],
          },
          {
            team_id: 0,
            team_name: 'Team4',
            waiting: 0,
            player: [null, null],
          },
        ],
      },
      {
        division_id: 11850,
        division_name: 'Coed 18-U Gold',
        format: 2,
        team: [
          {
            team_id: 108329,
            team_name: 'Team1',
            waiting: 0,
            player: [
              {
                avp_id: 100009153,
                first_name: 'Mia',
                last_name: 'Cabarloc',
                city: 'Saratoga',
                state_code: 'CA',
                status: 'Available',
                profile_pic: '',
                team_id: 108329,
                points: '0 pts',
              },
              {
                avp_id: 100009154,
                first_name: 'Olivia ',
                last_name: 'Rook ',
                city: 'Arlington',
                state_code: 'TX',
                status: 'Available',
                profile_pic: '',
                team_id: 108329,
                points: '0 pts',
              },
            ],
          },
          {
            team_id: 0,
            team_name: 'Team1',
            waiting: 0,
            player: [null, null],
          },
          {
            team_id: 0,
            team_name: 'Team2',
            waiting: 0,
            player: [null, null],
          },
          {
            team_id: 0,
            team_name: 'Team3',
            waiting: 0,
            player: [null, null],
          },
          {
            team_id: 0,
            team_name: 'Team4',
            waiting: 0,
            player: [null, null],
          },
        ],
      },
      {
        division_id: 11851,
        division_name: 'Coed 18-U Silver',
        format: 2,
        team: [
          {
            team_id: 108330,
            team_name: 'Team1',
            waiting: 0,
            player: [
              {
                avp_id: 100009155,
                first_name: 'Madison',
                last_name: 'Hess',
                city: 'Houston',
                state_code: 'TX',
                status: 'Available',
                profile_pic: '',
                team_id: 108330,
                points: '50 pts',
              },
              null,
            ],
          },
          {
            team_id: 0,
            team_name: 'Team1',
            waiting: 0,
            player: [null, null],
          },
          {
            team_id: 0,
            team_name: 'Team2',
            waiting: 0,
            player: [null, null],
          },
          {
            team_id: 0,
            team_name: 'Team3',
            waiting: 0,
            player: [null, null],
          },
          {
            team_id: 0,
            team_name: 'Team4',
            waiting: 0,
            player: [null, null],
          },
        ],
      },
    ],
  },
};
