//dashboard
export const DASHBOARD_TYPE_1 = "DASHBOARD_TYPE_1";
export const DASHBOARD_TYPE_2 = "DASHBOARD_TYPE_2";
export const DASHBOARD_TYPE_3 = "DASHBOARD_TYPE_3";
export const DASHBOARD_TYPE_4 = "DASHBOARD_TYPE_4";
export const DASHBOARD_TYPE_5 = "DASHBOARD_TYPE_5";
export const DASHBOARD_TYPE_6 = "DASHBOARD_TYPE_6";
export const DASHBOARD_TYPE_7 = "DASHBOARD_TYPE_7";
export const DASHBOARD_TYPE_LOADING = "DASHBOARD_TYPE_LOADING";
export const DASHBOARD_TYPE_ERROR = "DASHBOARD_TYPE_ERROR";

//list component loaders
export const PLAYER_LOADING_TYPE = "PLAYER_LOADING_TYPE";
export const MANGER_LOADING_TYPE = "MANGER_LOADING_TYPE";
export const EVENT_LOADING_TYPE = "EVENT_LOADING_TYPE";
export const REG_LOADING_TYPE = "REG_LOADING_TYPE";
export const SCORE_LOADING_TYPE = "SCORE_LOADING_TYPE";
export const TEMPLATE_LOADING_TYPE = "TEMPLATE_LOADING_TYPE";

//address
export const FILTER_ADDRESSES = "FILTER_ADDRESSES";
export const FILTER_ADDRESSES_CLEAR = "FILTER_ADDRESSES_CLEAR";

//contacts
export const FILTER_CONTACTS = "FILTER_CONTACTS";
export const FILTER_CONTACTS_CLEAR = "FILTER_CONTACTS_CLEAR";

//loading
export const SET_LOADING = "SET_LOADING";

//event profile data
export const EVENT_PROFILE_DATA = "EVENT_PROFILE_DATA";
export const SAVED_EVENT_DATA = "SAVED_EVENT_DATA";

// Profile Active History Area

//1. filter search of profile active history
export const FILTERED_ACTIVE_HISTORY_DATA = "FILTERED_ACTIVE_HISTORY_DATA";

//2. clear search of profile active history
export const CLEAR_FILTERED_ACTIVE_HISTORY_DATA =
  "CLEAR_FILTERED_ACTIVE_HISTORY_DATA";

// 3. Sort active history data title
export const SORT_ACTIVE_HISTORY_DATA_TITLE = "SORT_ACTIVE_HISTORY_DATA_TITLE";

//4. Unsorted active history data
export const UNSORTED_ACTIVE_HISTORY_DATA = "UNSORTED_ACTIVE_HISTORY_DATA";

// 5. Sort active history data division
export const SORT_ACTIVE_HISTORY_DATA_DIVISION =
  "SORT_ACTIVE_HISTORY_DATA_DIVISION";

// 6. Sort active history data finish
export const SORT_ACTIVE_HISTORY_DATA_FINISH =
  "SORT_ACTIVE_HISTORY_DATA_FINISH";

// 7. Sort active history data points
export const SORT_ACTIVE_HISTORY_DATA_POINTS =
  "SORT_ACTIVE_HISTORY_DATA_POINTS";

// 8. Sort active history data partner
export const SORT_ACTIVE_HISTORY_DATA_PARTNER =
  "SORT_ACTIVE_HISTORY_DATA_PARTNER";

// 9. Sort active history data date
export const SORT_ACTIVE_HISTORY_DATA_DATE = "SORT_ACTIVE_HISTORY_DATA_DATE";

//auth constants

export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const LOGOUT = "LOGOUT";
export const PROFILE_STATUS = "PROFILE_STATUS";
export const SET_SIDEBAR_DISABLED = "SET_SIDEBAR_DISABLED";
export const SET_DISABLED_MESSAGE = "SET_DISABLED_MESSAGE";
export const LOGIN_FAIL_MESSAGE = "LOGIN_FAIL_MESSAGE";
export const SET_SIDEBAR_MAX = "SET_SIDEBAR_MAX";
export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const FORGOT_PASSWORD_LOADING = "FORGOT_PASSWORD_LOADING";
export const FORGOT_PASS_MSG_NULL = "FORGOT_PASS_MSG_NULL";

// new manager profile
export const SAVED_MANAGER_DATA = "SAVED_MANAGER_DATA";
export const FILTERED_MANAGER_DATA = "FILTERED_MANAGER_DATA";
export const CLEAR_FILTERED_MANAGER_DATA = "CLEAR_FILTERED_MANAGER_DATA";
export const SORT_MANAGER_DATA_TITLE = "SORT_MANAGER_DATA_TITLE";
export const UNSORTED_MANAGER_DATA = "UNSORTED_MANAGER_DATA";
export const SORT_MANAGER_DATA_DIVISION = "SORT_MANAGER_DATA_DIVISION";
export const SORT_MANAGER_DATA_FINISH = "SORT_MANAGER_DATA_FINISH";
export const SORT_MANAGER_DATA_POINTS = "SORT_MANAGER_DATA_POINTS";
export const SORT_MANAGER_DATA_PARTNER = "SORT_MANAGER_DATA_PARTNER";
export const SORT_MANAGER_DATA_DATE = "SORT_MANAGER_DATA_DATE";
export const GET_MANAGER_ERROR = "GET_MANAGER_ERROR";

// create manager
export const CREATE_MANAGER = "CREATE_MANAGER";

// get manager by id (data)
export const GET_MANAGER_BY_ID = "GET_MANAGER_BY_ID";
export const GET_MANAGER_BY_ID_LIST = "GET_MANAGER_BY_ID_LIST";

//get all managers data
export const GET_MANAGERS_ALL = "GET_MANAGERS_ALL";
export const GET_MANAGERS_ALL_ERROR = "GET_MANAGERS_ALL_ERROR";

//set create manager api loading
export const CREATE_PROMOTER_LOADING = "CREATE_PROMOTER_LOADING";

export const CREATE_MANAGER_ERROR = "CREATE_MANAGER_ERROR";
export const EDIT_MANAGER_ERROR = "EDIT_MANAGER_ERROR";
export const CREATE_NEW_MANAGER_ERROR = "CREATE_NEW_MANAGER_ERROR";

//player profile
export const SAVED_PLAYER_DATA = "SAVED_PLAYER_DATA";
export const FILTERED_PROFILE_DATA = "FILTERED_PROFILE_DATA";
export const CLEAR_FILTERED_PROFILE_DATA = "CLEAR_FILTERED_PROFILE_DATA";
export const SORT_PROFILE_DATA_TITLE = "SORT_PROFILE_DATA_TITLE";
export const UNSORTED_PROFILE_DATA = "UNSORTED_PROFILE_DATA";
export const SORT_PROFILE_DATA_DIVISION = "SORT_PROFILE_DATA_DIVISION";
export const SORT_PROFILE_DATA_FINISH = "SORT_PROFILE_DATA_FINISH";
export const SORT_PROFILE_DATA_POINTS = "SORT_PROFILE_DATA_POINTS";
export const SORT_PROFILE_DATA_PARTNER = "SORT_PROFILE_DATA_PARTNER";
export const SORT_PROFILE_DATA_DATE = "SORT_PROFILE_DATA_DATE";

export const GET_ALL_PLAYERS = "GET_ALL_PLAYERS";
export const GET_PLAYER_BY_ID = "GET_PLAYER_BY_ID";
export const UPDATE_PLAYER_ID = "UPDATE_PLAYER_ID";
export const GET_PLAYER_HISTORY = "GET_PLAYER_HISTORY";
export const ON_EDIT_DIVISION_SAVE = "ON_EDIT_DIVISION_SAVE";
export const GET_ALL_PLAYERS_ERROR = "GET_ALL_PLAYERS_ERROR";

// event
export const FILTERED_EVENT_DATA = "FILTERED_EVENT_DATA";
export const CLEAR_FILTERED_EVENT_DATA = "CLEAR_FILTERED_EVENT_DATA";
export const SORT_EVENT_DATA_NAME = "SORT_EVENT_DATA_NAME";
export const UNSORTED_EVENT_DATA = "UNSORTED_EVENT_DATA";
export const SORT_EVENT_DATA_STARTS_ON = "SORT_EVENT_DATA_STARTS_ON";
export const SORT_EVENT_DATA_STATUS_LABLE = "SORT_EVENT_DATA_STATUS_LABLE";
export const SORT_EVENT_DATA_POINTS = "SORT_EVENT_DATA_POINTS";
export const SORT_EVENT_DATA_PARTNER = "SORT_EVENT_DATA_PARTNER";
export const SORT_EVENT_DATA_ADDRESS = "SORT_EVENT_DATA_ADDRESS";
export const CREATE_TOURNAMENT_ERROR = "CREATE_TOURNAMENT_ERROR";
export const GENERATE_SCHEDULE_RESPONSE = "GENERATE_SCHEDULE_RESPONSE";
export const GENERATE_SCHEDULE_ERROR = "GENERATE_SCHEDULE_ERROR";
export const CLEAR_SCHEDULE_MESSAGE = "CLEAR_SCHEDULE_MESSAGE";
export const GENERATE_SCHEDULE_DIV_RESPONSE = "GENERATE_SCHEDULE_DIV_RESPONSE";
export const GENERATE_SCHEDULE_DIV_ERROR = "GENERATE_SCHEDULE_DIV_ERROR";
export const CLEAR_DIV_SCHEDULE_MESSAGE = "CLEAR_DIV_SCHEDULE_MESSAGE";
export const EDIT_EVENT_ERROR = "EDIT_EVENT_ERROR";
export const EDIT_DIVISION_ERROR = "EDIT_DIVISION_ERROR";
export const GET_TOURNAMENT_ALL_ERROR = "GET_TOURNAMENT_ALL_ERROR";

export const SORT_EVENT_DATA_NAME_REVERSE = "SORT_EVENT_DATA_NAME_REVERSE";
export const SORT_EVENT_DATA_STARTS_ON_REVERSE =
  "SORT_EVENT_DATA_STARTS_ON_REVERSE";
export const SORT_EVENT_DATA_STATUS_LABLE_REVERSE =
  "SORT_EVENT_DATA_STATUS_LABLE_REVERSE";
export const SORT_EVENT_DATA_ADDRESS_REVERSE =
  "SORT_EVENT_DATA_ADDRESS_REVERSE";

export const SEND_DIVISION_DATA_TO_EVENT = "SEND_DIVISION_DATA_TO_EVENT";
export const GET_TOURNAMENT_DIVISIONS = "GET_TOURNAMENT_DIVISIONS";

export const UPDATE_EVENT_ID = "UPDATE_EVENT_ID";
export const TEMPLATE_NAME_AVAILABLE = "TEMPLATE_NAME_AVAILABLE";
export const TEMPLATE_NAME_TAKEN = "TEMPLATE_NAME_TAKEN";
export const TEMPLATE_NAME_TAKEN_FALSE = "TEMPLATE_NAME_TAKEN_FALSE";
export const CLEAR_TOURNAMENT_DATA = "CLEAR_TOURNAMENT_DATA";
export const CLEAR_TEMPLATE_NAME = "CLEAR_TEMPLATE_NAME";

// template data array
export const ADD_TO_TEMPLATE_DATA = "ADD_TO_TEMPLATE_DATA";
export const REMOVE_FROM_TEMPLATE_DATA = "REMOVE_FROM_TEMPLATE_DATA";
export const TEMPLATE_DATA_TO_NULL = "TEMPLATE_DATA_TO_NULL";

// division data array
export const ADD_TO_DIVISION_DATA = "ADD_TO_DIVISION_DATA";
export const REMOVE_FROM_DIVISION_DATA = "REMOVE_FROM_DIVISION_DATA";
export const DIVISION_DATA_TO_NULL = "DIVISION_DATA_TO_NULL";

// change early bird date from event to division
export const CHANGE_EARLY_BIRD_DATE = "CHANGE_EARLY_BIRD_DATE";

//event format
export const SAVED_EVENT_FORMAT_DATA = "SAVED_EVENT_FORMAT_DATA";

// event dropdown data
export const CALL_EVENT_DROPDOWN_DATA = "CALL_EVENT_DROPDOWN_DATA";

//event addresses
export const GET_EVENT_ADDRESSES = "GET_EVENT_ADDRESSES";

//set address id
export const SET_ADDRESS_ID = "SET_ADDRESS_ID";
export const SET_ADDRESS_ID_ERROR = "SET_ADDRESS_ID_ERROR";

//create tournament
export const CREATE_TOURNAMENT = "CREATE_TOURNAMENT";

//get tournament data by id
export const GET_TOURNAMENT_BY_ID = "GET_TOURNAMENT_BY_ID";

// tournament list data
export const GET_TOURNAMENT_ALL = "GET_TOURNAMENT_ALL";

//template division
export const SAVED_DIVISION_DATA = "SAVED_DIVISION_DATA";
export const SAVED_POOLS_DATA = "SAVED_POOLS_DATA";

// template list
export const FILTERED_TEMPLATE_LIST_DATA = "FILTERED_TEMPLATE_LIST_DATA";
export const CLEAR_FILTERED_TEMPLATE_LIST_DATA =
  "CLEAR_FILTERED_TEMPLATE_LIST_DATA";
export const SORT_TEMPLATE_LIST_DATA_TITLE = "SORT_TEMPLATE_LIST_DATA_TITLE";
export const UNSORTED_TEMPLATE_LIST_DATA = "UNSORTED_TEMPLATE_LIST_DATA";
export const SORT_TEMPLATE_LIST_DATA_DIVISION =
  "SORT_TEMPLATE_LIST_DATA_DIVISION";
export const SORT_TEMPLATE_LIST_DATA_FINISH = "SORT_TEMPLATE_LIST_DATA_FINISH";
export const SORT_TEMPLATE_LIST_DATA_POINTS = "SORT_TEMPLATE_LIST_DATA_POINTS";
export const SORT_TEMPLATE_LIST_DATA_PARTNER =
  "SORT_TEMPLATE_LIST_DATA_PARTNER";
export const SORT_TEMPLATE_LIST_DATA_DATE = "SORT_ACTIVE_HISTORY_DATA_DATE";

//reg event player list
export const GET_REG_ALL = "GET_REG_ALL";
export const GET_REG_BY_ID = "GET_REG_BY_ID";
export const GET_TEAM_DATA_BY_ID = "GET_TEAM_DATA_BY_ID";
export const SET_TEAM_DATA_LOADING = "SET_TEAM_DATA_LOADING";
export const GET_PLAYERS_DATA = "GET_PLAYERS_DATA";
export const SET_REMOVE_PLAYER_LOADING = "SET_REMOVE_PLAYER_LOADING";
export const REMOVE_PLAYER_FROM_TEAM = "REMOVE_PLAYER_FROM_TEAM";
export const SET_ADD_PLAYER_LOADING = "SET_ADD_PLAYER_LOADING";
export const ADD_PLAYER_TO_TEAM = "ADD_PLAYER_TO_TEAM";
export const SET_REG_STATUS_TO_LOADING = "SET_REG_STATUS_TO_LOADING";
export const SET_REG_TEAM_STATUS = "SET_REG_TEAM_STATUS";
export const REMOVE_EDIT_PLAYER_FROM_TEAM = "REMOVE_EDIT_PLAYER_FROM_TEAM";
export const GET_PLAYERS_DATA_LOADING = "GET_PLAYERS_DATA_LOADING";
export const GET_REG_ALL_ERR = "GET_REG_ALL_ERR";
export const GET_REG_BY_ID_ERR = "GET_REG_BY_ID_ERR";
export const GET_PLAYERS_DATA_ERROR = "GET_PLAYERS_DATA_ERROR";
export const EXCEL_ERROR = "EXCEL_ERROR";
export const EXCEL_ERROR_CLEAR = "EXCEL_ERROR_CLEAR";
export const GET_REGISTERED_DIVISIONS = "GET_REGISTERED_DIVISIONS";
export const GET_REGISTERED_DIVISIONS_TO_NULL =
  "GET_REGISTERED_DIVISIONS_TO_NULL";
export const GET_REGISTERED_DIVISIONS_LOADING =
  "GET_REGISTERED_DIVISIONS_LOADING";
export const CHANGE_DIVISION_FOR_TEAM_RESPONSE =
  "CHANGE_DIVISION_FOR_TEAM_RESPONSE";
export const CHANGE_DIVISION_FOR_TEAM_RESPONSE_NULL =
  "CHANGE_DIVISION_FOR_TEAM_RESPONSE_NULL";
export const CHANGE_DIVISION_FOR_TEAM_RESPONSE_LOADING =
  "CHANGE_DIVISION_FOR_TEAM_RESPONSE_LOADING";
export const GENERATE_INVOICE_MESSAGE = "GENERATE_INVOICE_MESSAGE";
export const GENERATE_INVOICE_MESSAGE_NULL = "GENERATE_INVOICE_MESSAGE_NULL";
export const REG_TEAM_PLAYER_STATUS_LOADING = "REG_TEAM_PLAYER_STATUS_LOADING";
export const REMIND_PAYMENT_FOR_TEAM_LOADING =
  "REMIND_PAYMENT_FOR_TEAM_LOADING";
export const REG_TEAM__STATUS_LOADING = "REG_TEAM__STATUS_LOADING";
export const GET_TEAM_PAID_AMOUNT = "GET_TEAM_PAID_AMOUNT";
// export const GET_PLAYERS_DATA_TO_NULL = 'GET_PLAYERS_DATA_TO_NULL';

//templates
export const GET_TEMP_ALL = "GET_TEMP_ALL";
export const GET_TEMP_ALL_ERR = "GET_TEMP_ALL_ERR";
export const GET_TEMPLATE_BY_ID = "GET_TEMPLATE_BY_ID";
export const UPDATE_TEMPLATE_ID = "UPDATE_TEMPLATE_ID";
export const CREATE_DIVISION_TEMPLATE = "CREATE_DIVISION_TEMPLATE";
export const EDIT_DIV_TEMPLATE_ERROR = "EDIT_DIV_TEMPLATE_ERROR";
export const DUPLICATE_DIV_TEMPLATE_ERROR = "DUPLICATE_DIV_TEMPLATE_ERROR";
export const UPLOAD_EXCEL = "UPLOAD_EXCEL";
export const EXCEL_LOADING = "EXCEL_LOADING";

///pools template
export const CREATE_POOLS_TEMPLATE = "CREATE_POOLS_TEMPLATE";
export const CREATE_POOLS_TEMPLATE_LOADING = "CREATE_POOLS_TEMPLATE_LOADING";
export const CREATE_POOLS_TEMPLATE_LOADING_FALSE =
  "CREATE_POOLS_TEMPLATE_LOADING_FALSE";
export const GET_POOLS_TEMPLATE_BY_ID = "GET_POOLS_TEMPLATE_BY_ID";
export const UPDATE_POOL_TEMPLATE = "UPDATE_POOL_TEMPLATE";
export const UPDATE_POOL_TEMPLATE_LOADING = "UPDATE_POOL_TEMPLATE_LOADING";
export const POOLS_TAKEN_TEMPLATE = "POOLS_TAKEN_TEMPLATE";
export const POOLS_NOT_TAKEN_TEMPLATE = "POOLS_NOT_TAKEN_TEMPLATE";
export const GET_POOLS_TEMPLATE_BY_ID_ERROR = "GET_POOLS_TEMPLATE_BY_ID_ERROR";
export const UPDATE_POOL_TEMPLATE_ERROR = "UPDATE_POOL_TEMPLATE_ERROR";
export const CREATE_POOLS_TEMPLATE_ERROR = "CREATE_POOLS_TEMPLATE_ERROR";

//points template
export const CREATE_POINTS_TEMPLATE = "CREATE_POINTS_TEMPLATE";
export const CREATE_POINTS_TEMPLATE_LOADING = "CREATE_POINTS_TEMPLATE_LOADING";
export const GET_POINTS_TEMPLATE_BY_ID = "GET_POINTS_TEMPLATE_BY_ID";
export const UPDATE_POINTS_TEMPLATE = "UPDATE_POINTS_TEMPLATE";
export const POINTS_TAKEN_TEMPLATE = "POINTS_TAKEN_TEMPLATE";
export const POINTS_NOT_TAKEN_TEMPLATE = "POINTS_NOT_TAKEN_TEMPLATE";
export const CREATE_POINTS_TEMPLATE_ERROR = "CREATE_POINTS_TEMPLATE_ERROR";
export const GET_POINTS_TEMPLATE_BY_ID_ERROR =
  "GET_POINTS_TEMPLATE_BY_ID_ERROR";
export const UPDATE_POINTS_TEMPLATE_ERROR = "UPDATE_POINTS_TEMPLATE_ERROR";

//scores
export const GET_SCORE_TOURNAMENTS = "GET_SCORE_TOURNAMENTS";
export const GET_SCORES_BY_ID = "GET_SCORES_BY_ID";
export const SCORE_EDIT_ERROR = "SCORE_EDIT_ERROR";
export const CLEAR_SCORE_ERROR = "CLEAR_SCORE_ERROR";
export const GET_SCORE_TOURNAMENTS_ERROR = "GET_SCORE_TOURNAMENTS_ERROR";

//tournaments
export const GET_TOURNAMENTS = "GET_TOURNAMENTS";
export const TOURNAMENT_LOADING_TYPE = "TOURNAMENT_LOADING_TYPE";
export const GET_TOURNAMENTS_ERROR = "GET_TOURNAMENTS_ERROR";

//pools screen
export const GET_EVENT_POOL_SCHEDULE = "GET_EVENT_POOL_SCHEDULE";
export const GET_EVENT_POOL_SCHEDULE_LOADING =
  "GET_EVENT_POOL_SCHEDULE_LOADING";
export const GET_POOLS_ALL = "GET_POOLS_ALL";

//brackets
export const GENERATE_BRACKET = "GENERATE_BRACKET";
export const GENERATE_BRACKET_ERROR = "GENERATE_BRACKET_ERROR";
export const GET_BRACKET = "GET_BRACKET";
export const RESET_BRACKET_MESSAGES = "RESET_BRACKET_MESSAGES";
export const EDIT_BRACKET_ERROR = "EDIT_BRACKET_ERROR";
export const EDIT_BRACKET = "EDIT_BRACKET";
export const SET_DIVISION_DATA = "SET_DIVISION_DATA";
export const CLOSE_BRACKET = "CLOSE_BRACKET";
export const CLOSE_BRACKET_ERROR = "CLOSE_BRACKET_ERROR";

//stripe
export const ADD_STRIPE_ACCOUNT_ERROR = "ADD_STRIPE_ACCOUNT_ERROR";
export const CLEAR_STRIPE_ERROR_MESSAGES = "CLEAR_STRIPE_ERROR_MESSAGES";
export const GET_STRIPE_ACCOUNT = "GET_STRIPE_ACCOUNT";
export const GET_STRIPE_ACCOUNT_ERROR = "GET_STRIPE_ACCOUNT_ERROR";
export const ADD_STRIPE_ACCOUNT_MESSAGE = "ADD_STRIPE_ACCOUNT_MESSAGE";
